#!/usr/bin/env python3
"""Append OM4-OM7 (refinamentos Cluster 2) ao Operating Manual CSV. Idempotente (dedup por lens_id)."""
MAN = "results/l2_bpt_reader_operating_manual.csv"
ROWS = [
    ["OM4","indicator_confluence_as_reading","INDICATOR","refines:bubble_polarity(E2);overbought_in_bear(C5);capitulation_climax(A8);indicators_identify_macro_top(I4)","CONTRAST_LENS;CONDITIONAL_SUPPORT","sempre - indicador (sell/buy bubbles, RSI bull/bear-div, NAS, SMC) PERGUNTA capitulacao/absorcao/exaustao/mudanca-de-carater/whipsaw; NAO classifica TAKE/SKIP","confluencia (sell-bubble climax no low + RSI bull-div + NAS-bottom) inverte leitura form-only de range=wall para capitulacao=fuel (fix do 5627)","indicador como gate per-trade afunda winners (I4); sell-bubble-no-low sozinho nao decide (3929-trap e 3949-runner tem assinatura parecida; whipsaw OM6 separa)","5627 (capitulacao no indicador, form-only leu wall); 3929 vs 3949 (mesma assinatura, timing separa)","gate per-trade; equal-veto; indicador isolado como verdade","layer causal em l2_bpt_causal_indicator_layer.py (bubbles+RSI causais; NAS/SMC UNRELIABLE no frozen RAW exigem fonte pine_labels); evidencia-pergunta no pacote cego","visual post-audit cluster 2 + audit 9f7326f"],
    ["OM5","washout_runner_vs_compression_runner","MICRO/AUCTION","refines:OM1;capitulation_climax(A8)","CONTRAST_LENS","ao decidir se long em macro negativo se desenvolve - ha DOIS arquetipos de runner","distingue (A) washout-runner (queda madura->capitulacao->reabsorcao->expansao) de (B) compression-runner (range apertado sob supply->defesa lateral->coil->expansao); 5627 veio de so ter o tipo A -> tratou compressao-sob-supply como wall era fuel","5627 (compression-runner lido como wall por falta do arquetipo B)","5826/4401/1522/3949 (A washout) vs 5627 (B compression)","gate; presumir que todo range-sob-supply e um dos dois (pode ser wall real)","discriminar A vs B por forma (climax+reabsorcao vs lateral-defendido+coil) + OM4; leitura humana","visual post-audit cluster 2 ep 5627"],
    ["OM6","bottom_attempt_whipsaw_vs_trap","MICRO","refines:leg_maturity(D6);OM3","CONTRAST_LENS;WARNING_ONLY","ao rotular um caso que falha em macro negativo perto de possivel fundo","separa bottom-attempt-whipsaw (perto de fundo macro real + sinais de tentativa de reversao mas ESTE entry falha por timing/whipsaw) de bear-pullback-trap limpo (sem fundo perto, distribuicao); natureza diferente mesmo que ambos falhem","1873 (lido trap MED-ALTA era bottom-attempt-whipsaw); 3929 (tentativa 3 dias antes do 3949)","1873, 3929 (whipsaw perto de fundo) vs trap de distribuicao limpo","gate de TAKE (whipsaw ainda falha o entry); chamar todo loser-em-bear de trap","proximidade de fundo macro + sinais de reversao tentada (OM4) + entry-timing; flag de natureza nao de trade","visual post-audit cluster 2 ep 1873/3929"],
    ["OM7","confidence_calibration_ambiguous_zones","READING","refines:todas-as-lentes-de-natureza","WARNING_ONLY","sempre que a leitura cair em zona ambigua: range-apertado-sob-supply, bottom-attempt, compressao-antes-da-expansao, entry-perto-de-zona-conflitante","baixa a confianca DECLARADA mesmo quando a direcao parece clara - nessas zonas a NATUREZA e ambigua (5627 levou ALTA-confianca e errou)","5627 (ALTA-confianca em range-sob-supply errado); 1873 (MED-ALTA em bottom-whipsaw)","5627, 1873","desculpa para nao ler; e calibracao nao recusa","rebaixar confianca a MEDIA nessas 4 zonas por default; leitura humana","visual post-audit cluster 2"],
]
have = {ln.split("|")[0] for ln in open(MAN).read().splitlines()[1:] if "|" in ln}
new = [r for r in ROWS if r[0] not in have]
if new:
    data = open(MAN).read()
    with open(MAN, "a") as f:
        if not data.endswith("\n"): f.write("\n")
        for r in new:
            assert len(r) == 12, r
            f.write("|".join(r) + "\n")
print(f"OM4-OM7: {len(new)} adicionadas ({[r[0] for r in new]}); manual = {len(open(MAN).read().splitlines())-1} lentes")
