-- memory_delta_20260720_live_audit_fixes
-- Auditoria do codigo live + correcoes de erros/fluidez realtime (aprovado Cris).
-- Sem secrets. ASCII. Sem ponto-e-virgula no texto.
-- ROLLBACK (via SQL Editor): apagar memory_items com a tag deste seed.
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('live_code_audit_fixes_20260720')::uuid, 'private', 'private', 'project',
  'Auditoria do codigo live 2026-07-20: 5 fixes de bugs/fluidez realtime (perda de dados, alertas perdidos, herd)',
  'Auditoria read-only de todo o codigo live + correcoes aprovadas pelo Cris, ordem #3 #6 #1 #2 #5. FIXES APLICADOS E VERIFICADOS (commits 24aa194 + e6e1977): #1 CRITICO perda-de-dados: bar_store._jl devolvia lista vazia numa linha corrompida e append_tf reescrevia o raw_4h/raw_1h multi-ano inteiro com ~8 barras - agora _jl salta linhas mas + guard anti-truncamento (recusa reescrever ficheiro canonico retain=None se parseou menos de 50pct das linhas). #2 regime_engine append nao-atomico corrompia RAW (linha meio-escrita) - agora tmp+os.replace atomico com tmp unico por-pid - e _load_last_t fail-open (devolvia 0 -> phase=0 -> rejeitava TODAS as barras 4H -> HARD_STOP) agora recua de linha corrompida e devolve None em ilegivel (aborta loud). #3 ALERT-ONLY o pior: Cp/AMD/price-shock marcavam dedup INDEPENDENTE do envio Telegram ter sucesso -> blip de rede = entrada perdida sem recuperacao - agora marca dedup SO se entregue, senao re-tenta proximo ciclo (padrao do news_escalate) - AMD re-tenta ping1 de ARMED falhados. #5 thundering-herd: em outage do bar-store todos os consumidores caiam para MCP proprio ao mesmo tempo e martelavam o 9222 - store_reader.fallback_ok = rate-limit partilhado 1 por 20s + jitter fail-open, gate em context_mtf/micro/confluence + Cp (regime NAO, e MCP-primario). #6 rotacao de logs incluia os 4 mais frequentes que faltavam (shock_cycle 30s router amd journal). DECISOES: #4 price-shock re-verifica tab 5 cada ciclo = MANTIDO (o chart_get_state e SAFETY nao desperdicio - uma tab a mudar partiu o feed hoje - custo inerente ao 2o leitor CDP que precisa da barra 5M em formacao). #7 E2 read offset por-linha = DEFERIDO para quando o E2 promover (shadow-only hoje, bug so morde na promocao). Padrao reforcado: fail-loud nao fail-silent - marcar estado so apos sucesso real.',
  array['seed:memory_delta_20260720_live_audit_fixes','auditoria','live','fixes','bar-store','telegram-retry','anti-herd','fluidez'],
  'commits 24aa194 + e6e1977 (auditoria live + fixes)', 'active')
on conflict (id) do nothing;
