-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260804_liquidity_axis
-- ============================================================================
-- Eixo liquidez/manipulacao E0+E2 LIVE (voz ON por ordem Cris). 1 row. Idempotente.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260804_liquidity_axis:memory_items:axis')::uuid,
  'product', 'internal', 'project',
  'EIXO LIQUIDEZ/MANIPULACAO LIVE (Cris: desenho B aprovado + VOZ ON IMEDIATA, 2026-08-04): axes.liquidity no E0 + voz de 1a classe no reader E2 que SOBREPOE o rotulo de perna atrasado — fix estrutural do Judas 08:03 e do leg-lag 11:30',
  'MOTIVO (2 falhas no MESMO dia, direcoes opostas, mesma causa-raiz — Cris: "aceita ser manipulado ingenuamente ainda"): o reader lia momentum+rotulo de perna e nao lia mecanica de liquidez. 08:03 surfou LONG para dentro da supply declarada (Judas; compra sendo ABSORVIDA no iman; Cris -450 USD); 11:30 recusou o reclaim genuino pos-sweep chamando-lhe faca (rotulo de perna ATRASADO) e o preco correu +24pts ate 4076 — leg-lag provado forward. IMPLEMENTADO (aceitacao ANTES de live, no proprio dia): (1) alert-bridge/context_liquidity.py -> axes.liquidity no dossie E0 (cadencia bar-close 15M, stateless 480 barras): vigia PDH/PDL/PWH/PWL + extremos de sessao (UTC FIT Asia23-07/Londres07-12/NY12-21) + pivos k=3 dedup; sweep = pavio alem + close de volta <=3 barras -> FSM por lado SWEPT->RECLAIMED->HOLDING(2 closes)->CONTINUATION/FAILED + lado PRESO (lows varridos = shorts presos = combustivel up). (2) Classificacao do movimento: INICIATIVA_PARA_IMAN (para iman contrario nao-preenchido <=1.5ATR sem sequencia provada = manipulacao-provavel, REBAIXA conviccao momentum — fix Judas) vs DESLOCAMENTO_POS_SWEEP (afasta-se da liquidez varrida = genuino, SOBREPOE o rotulo de perna — fix leg-lag) vs MISTO (hold+ mas iman ao alcance = exigir teste-e-rejeicao no iman, principio GT#1) vs NEUTRO. Significancia por RAID (principio anti-rocadela: so conta nivel 1a-ordem OU excursao >=1.0 ATR) + chase-guard (CONTINUATION >1.5 ATR alem do nivel = janela passada, principio entrada-ancorada). R8 1a-quebra=manipulacao/2a=confirmacao agora tambem chega ao reader como voz. (3) e2_quality: LIQUIDITY_RULE no READ_SYS + seccao "# LIQUIDEZ / MANIPULACAO" no briefing apos MAPA DO TRADER; "nao e veto nem aprovacao automatica — mas em contradicao com o rotulo da perna, esta voz manda". Flag E2_LIQUIDITY_VOICE default ON (=0 restaura byte-identico, golden verificado). ACEITACAO PASS: (a) 08:03 => INICIATIVA_PARA_IMAN + zona-do-trader nomeada; (b) 11:30 => sweep 4046.61 + reclaim => DESLOCAMENTO_POS_SWEEP nos bares reais do store; (c) 34 recusas LONG resolvidas por preco: 27 facas, 25 MORTAS no detetor (92.6 pct knife-safety); 2 residuais DIVULGADOS ao Cris (24/07 12:32 e 31/07 04:17, cobertos por outras vozes: auction fraco / dead_zone conv16; criterio ajustado COM disclosure — apertar ate 0/27 seria fit-a-amostra); 0/7 winners resgatados (honesto: nenhum tinha sequencia-com-hold no momento do read); (e) golden byte-exato + e2 selftest+anchors PASS. FIT declarados p/ replay: RECLAIM_N=3 HOLD_BARS=2 REACH_ATR=1.5 RAID_MIN=1.0ATR SPENT=1.5ATR. VIGILANCIA FORWARD: faca promovida a surfaced = rollback imediato da voz por flag (eixo fica no dossie); medir 1 semana turn-capture (baseline 0/5) vs knife-safety + ancoragem do LLM. E0+E2 kickstarted; eixo vivo no dossie a ler o mercado (INICIATIVA_PARA_IMAN na subida pos-4084). Commit ba23b57.',
  array['seed:memory_delta_20260804_liquidity_axis','eixo-liquidez-manipulacao','axes-liquidity-e0','voz-1a-classe-e2','sweep-reclaim-hold-fsm','lado-preso','iniciativa-para-iman-vs-deslocamento-pos-sweep','raid-1atr-anti-rocadela','chase-guard','sobrepoe-rotulo-perna-leg-lag','fix-judas-0803','92pct-knife-safety-2-residuais-divulgados','voz-on-imediata-ordem-cris'],
  'alert-bridge/context_liquidity.py · context_engine.py · e2_quality.py · research/accept_liquidity_axis_20260804.py · project_liquidity_axis_e0_e2 · commit ba23b57',
  'active'
)
on conflict (id) do nothing;
commit;
