-- memory_delta_20260719_realtime_news_polymarket
-- Janela 2026-07-18/19: arquitetura realtime v2 + news price-first + Polymarket + padroes de execucao.
-- Fecha o gap desde o ultimo seed (2026-07-17). Sem secrets, sem params de edge, sem RAW. ASCII.
-- ROLLBACK: delete from memory_items where tags @> array['seed:memory_delta_20260719_realtime_news_polymarket'];
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('realtime_architecture_v2_20260718')::uuid, 'private', 'private', 'architecture',
  'Arquitetura realtime v2 do stack XAU (bar-store unico leitor CDP + event-driven + E2 via SDK + config unica) 2026-07-18',
  'Quatro fases executadas 2026-07-18 (mercado fechado, Cris aprovou todas). F1 BAR-STORE (com.cristrein.bar-store, 60s) = UNICO leitor MCP/CDP: OHLC 15M/1H/4H/1D + bubbles/NAS + snapshots pine_boxes/study_values por tab, 1 sessao MCP por tab, validacao unica. 4H/1H = RAW canonicos (research le os mesmos). Consumidores via alert-bridge/store_reader.py fresh()=heartbeat do store (nao idade da barra, cobre fim-de-semana). E0+Cp+regime+backfill = store-first com fallback MCP legado. F2 EVENT-DRIVEN: launchd WatchPaths (Cp acorda no append de bars_15m em segundos, regime no append de raw_4h); StartInterval como fallback; lag fecho->detecao caiu de <=15min para ~60-70s. F3 E2 READ VIA SDK: _read_sdk (anthropic, claude-opus-4-8, adaptive) atras de flag E2_READ_VIA=sdk + ANTHROPIC_API_KEY, INERTE ate Cris criar API key; default = CLI claude -p sessao Max. F4 CONFIG UNICA: alert-bridge/config_stack.py (DEAD_SESSIONS, timezone Lisboa) importado por e1/e2, fim do sync por comentario. Auditoria A+B+C (Cris pediu): stack saudavel, 0 crashes reais, zero contencao MCP provada (Cp/regime/E0 todos source:store); watchdog passou a cobrir caminho de ENTRADA (Receiver /health + Cloudflared pgrep) + bar-store tab_pin cache-first + rotacao diaria de logs heartbeat. Commits 4448ebf/56d1878/ee382bf/9671a24.',
  array['seed:memory_delta_20260719_realtime_news_polymarket','arquitetura','bar-store','event-driven','watchdog','realtime'],
  'memory/reference_live_stack_20260718.md · commits 4448ebf/56d1878/ee382bf/9671a24', 'active'),
 (md5('news_architecture_price_first_polymarket_20260719')::uuid, 'private', 'private', 'architecture',
  'Arquitetura de news / external factors price-first + coletor Polymarket (2026-07-18/19, tudo gratis)',
  'Doutrina Cris = price-first (o preco move ANTES dos feeds; news de alto impacto deve acionar rapido). alert-bridge/news_gate.py = gate unificado advisory (informa, NUNCA bloqueia), lido pelo E0; high_impact_now = BREAKING so (news fresca / choque de preco / release agendado). oil-shock e guerra-em-curso = contexto persistente, nao ligam breaking 24/7. GATILHO rapido sub-minuto: price_shock (tape 15M, 30s) + finnhub_gld_ws (WebSocket GLD ticks, so horas US), ambos Telegram gated por L1_PRODUCTION_AUTHORIZED (send_telegram NAO tem gate proprio, o caller gateia). CONTEXTO fresco lane 4min run_news_cycle.sh: finnhub_news (Reuters-tier) + geopolitical (GDELT keyless) + investinglive (RSS) + oil (FMP Brent) + polymarket -> news_escalate (escala 1x a headline breaking mais fresca, dedup+cooldown 10min, gate NEWS_ALERTS_AUTHORIZED, exclui price_shock/GLD que auto-alertam). CONTEXTO lento: fj_stream_ws (FinancialJuice WebSocket, FREE=10min atraso, nunca breaking) + POLYMARKET (novo 2026-07-19, Gamma API keyless): odds forward-looking dos drivers do ouro (Fed no-change, invasao Ira, Ormuz, recessao); filtro macro/geopolitico client-side; edge = o DELTA (shift >=5pp = evento a ser precificado antes do preco, entra no advisory, nunca liga breaking). Fincept avaliado -> so a ideia reusada, zero codigo deles. Watchdog = 17 componentes (inclui Bar-store, PriceShock, GLD-ws, FJ-ws, EF news, Polymarket, Receiver, Cloudflared). Segredos FINNHUB/FJ em root .env chmod 600 gitignored (FJ key foi exposta no chat, Cris deve rodar); Polymarket keyless. Commits 30045ce/4bdefb2/e13c44a/bbad1d6/c1d9ad5.',
  array['seed:memory_delta_20260719_realtime_news_polymarket','news','external-factors','price-shock','polymarket','price-first'],
  'memory/reference_live_stack_20260718.md · commit c1d9ad5 (Polymarket)', 'active'),
 (md5('execution_phase_patterns_multibroker_paper_20260719')::uuid, 'private', 'private', 'reference',
  'Padroes para a fase de EXECUCAO futura: abstracao multi-broker + motor de paper-trading (emular, nao copiar)',
  'Quando o stack sair de alert-only para execucao real, dois padroes arquiteturais valem (conceitos a emular, nao codigo a copiar, vistos ao avaliar terminais tipo Fincept/MRKT mas implementacao nossa): (1) Abstracao multi-broker = UMA interface de execucao (submit_order/cancel/positions/account/fills) com adaptadores por broker por tras; o motor de estrategia fala so a interface, trocar broker = trocar adaptador, isola vendor lock-in e permite testar o mesmo sinal em brokers diferentes. (2) Motor de paper-trading = simulador de fills (slippage/spread/latencia) que consome os MESMOS sinais que o live consumiria, escreve ledger paralelo, ponte segura antes de risco real. ORDEM OBRIGATORIA: paper primeiro, nenhum broker real antes de o paper validar a ponte sinal->ordem->fill->ledger. Casa com forward-arbitro e disciplina pre-mudanca (Plan agent para mudanca arquitetural). Gatilho para reabrir = decisao explicita do Cris de sair do alert-only. Nao abrir esta frente antes de fechar ciclos (WIP alto).',
  array['seed:memory_delta_20260719_realtime_news_polymarket','execucao','multi-broker','paper-trading','futuro'],
  'memory/reference_execution_phase_patterns.md', 'active')
on conflict (id) do nothing;
