begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260804_validator_asia_ath:memory_items:validator')::uuid,
  'product','internal','project',
  'VALIDADOR DE ENTRADA LIVE (Cris 2026-08-04 noite): daemon fulltime/realtime GO/ESPERA/INVALIDOU/DISTANTE nos niveis DECLARADOS do Cris (nunca propoe direcao), GO->Telegram entry/SL/alvo/RR + break-continuidade <4075 + plano SELL Asia (reteste 4090-4106 OU break, alvos 4045-60 -> 3995-4010 verdadeiro, analogo 30/07)',
  'CONTEXTO: Cris apos dia -4R: "meu maior problema e acertar os pontos de entrada, falta confianca; quero sistema como apoio e validacao". DECISAO: manter sistema de sinais (cedo p/ desistir do que esta em construcao) + VALIDADOR fulltime/realtime/paralelo. VALIDADOR (entry_validator.py, com.cristrein.entry-validator, EV_TG_AUTHORIZED=1): NAO decide direcao nem procura trades; pega nos niveis DECLARADOS no trader_map (zonas + nivel_confirmacao_short) e da em realtime DISTANTE/ESPERA/GO/INVALIDOU; GO = rejeicao impressa (regua da vela, 15M ou 1H) OU break do gatilho -> Telegram com entry/SL/alvo/RR; alerta SO nas transicoes p/ GO; INVALIDOU = preco aceite do outro lado; consome vela_no_nivel.decide+agg_1h+targets (nao reinventa); snapshot continuo entry_validator_status.json; selftest 6/6. BREAK-CONTINUIDADE na vela (check_break_continuation): fecho 15M decisivo <4075 -> sinal planeado entry=break/retest SL=swing+0.15ATR alvo=OB Detector abaixo; selftest 10/10. CANDLE-READER agora injeta leitura canonica de TODOS os indicadores (market_read 15M+1H) em CADA read de vela (ordem Cris: leitura permanente por vela). PLANO SELL ASIA 04->05/08: tese BEAR, ouro raramente desce direto; analogo 30/07 estudado barra-a-barra (topo 4120.5, 3-4 retestes lower-highs por ~10h pavios 46-67%, breakdown SO na Asia 01-03h -> 4075); hoje topo 4106 dived 4076; maior probabilidade = Asia reteste 4090-4106 (OB real, 4090-95 Cris = borda inf) -> lower high -> rejeicao = SHORT SL>4106.5; OU break <4075 = continuidade; ALVOS 4045-4060 -> 3995-4010 (ALVO VERDADEIRO ordem Cris); 3 canais Telegram armados (GO validador / rejeicao vela / confirmado Opus). Todos os daemons verificados live na reabertura.',
  array['seed:memory_delta_20260804_validator_asia_ath','validador-entrada-live-fulltime','go-espera-invalidou-distante','nunca-propoe-direcao','break-continuidade-4075','plano-sell-asia-reteste-4090-4106','alvo-verdadeiro-3995-4010','analogo-30-07-breakdown-asia','candle-reader-leitura-canonica-por-vela','manter-sinais-mais-validador'],
  'alert-bridge/entry_validator.py + candle_reader.py + vela_no_nivel.py · trader_map.json · project_entry_validator_live',
  'active'
),
(
  md5('seed:memory_delta_20260804_validator_asia_ath:memory_items:ath')::uuid,
  'product','internal','reference',
  'ATH XAU 2026 = 5597.91 (2026-01-28) + crash -> escada REAL de supplies HTF no OB Detector 240: 4382->4515->4541->4595->4718->4889->5016->5145->5419->5598 (verificado bars_1d 400d); guard-de-contaminacao que assumiu teto 4382 SEM ler dados = erro revertido; captura tab_pin estava CERTA',
  'AUDITORIA (ordem Cris "o simbolo da tab 4H e XAU, auditar porque deu erro"): as zonas OB 240 4515-5598 que marquei como "simbolo errado" SAO XAU REAL — ouro fez ATH 5597.91 em 2026-01-28 (zona OB 5566-5598 bate ao centimo) e crashou; 106 dias acima de 4500 (dez25-jun26); range 400d = 3245-5598. O MEU ERRO: assumi "XAU nunca negociou acima de 4382" com base na janela curta do chart atual SEM verificar bars_1d — mesmo pecado do dia (assumir em vez de ler) — e o guard de 8% que criei excluia zonas HTF REAIS (pior que o problema imaginario). REMOVIDO no proprio commit seguinte; nota de auditoria no codigo. A captura (bar_store_cycle -> tab_pin verifica simbolo XAUUSD + resolucao por tab) estava PERFEITA. GANHO: a escada completa de supplies HTF do crash agora esta mapeada e disponivel aos readers (contexto macro que ninguem lia); se o ouro estender acima de 4382, as proximas zonas ja sao conhecidas. LICAO (cicatriz): NUNCA assumir — ler os dados; qualquer "guard" baseado em assuncao nao-verificada e mais perigoso que o problema que imagina resolver.',
  array['seed:memory_delta_20260804_validator_asia_ath','ath-xau-5597.91-jan26','crash-2026-escada-supplies-htf','ob-240-e-xau-real','guard-contaminacao-erro-revertido','tab-pin-captura-certa','nunca-assumir-ler-dados','escada-4382-a-5598-mapeada'],
  'my-strategy/core/bar_store/store/bars_1d.jsonl · pine_boxes_240.json · alert-bridge/market_read.py · tab_pin.py · project_entry_validator_live',
  'active'
)
on conflict (id) do nothing;
commit;
