-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260804_copiloto_mapa_vela
-- ============================================================================
-- Copiloto fase 1: mapa do trader + vela-no-nivel (aceitacao dia 04/08 PASS 5/5). 1 row. Idempotente.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260804_copiloto_mapa_vela:memory_items:copiloto')::uuid,
  'product', 'internal', 'project',
  'COPILOTO fase 1 LIVE (Cris aprovou 2026-08-04): MAPA DO TRADER injetado no reader E2 + prefixo de CONFLITO + VELA-NO-NIVEL (leitura de barra nas zonas criticas) — aceitacao = o proprio dia 04/08, PASS 5/5',
  'FALHA MOTIVADORA (04/08, perda real 450 USD): o E2 surfou um LONG (08:03, 4063.36) para DENTRO da zona de venda PRE-DECLARADA do Cris (4066-4073, "subir a 4070/4080 pra virar") sem aviso de conflito — Cris seguiu-o e perdeu; as 09:00 a vela de absorcao imprimiu (tocou 4073.04, pavio 57 pct/0.82xATR, fechou 4068.28 = o short certo que o Cris identificou: "shortar ao final da vela das 9h em 4068.25") e NINGUEM a leu. Cris: "me atrapalha ao inves de me ajudar". CAUSA ESTRUTURAL: o mapa do trader nunca chegava ao reader (vivia na conversa e em vigias ad-hoc). DECISAO Cris: operar DUAS formas — sinais (continua, em construcao, merece tempo) + copiloto (amplifica o edge comprovado = o Cris). IMPLEMENTADO (desenho Plan aprovado -> aceitacao antes de live): (1) alert-bridge/trader_map.json = zonas/tese pre-declaradas (low/high/tese SHORT-LONG-NEUTRA/nota/criticidade/validade-expira-sozinha); atualizacao = Cris pede em chat/Telegram-bridge -> Claude edita + --validate; NUNCA editar sem instrucao explicita; mapa inicial supply 4066-4073 + OB premium 4101-4116 SHORT criticas. (2) e2_quality render_composite: seccao "# MAPA DO TRADER" apos o FRAME com regra ATENCAO-NAO-OBEDIENCIA (maxima atencao + sensibilidade de 1a rejeicao nas zonas; o trader pode estar errado — descrever a realidade; candidato contra-tese na zona = conviccao EXTRAORDINARIA + conflito por extenso); SEM mapa = render byte-identico (golden verificado). (3) notify_surfaced: prefixo deterministico "CONTRA A TUA LEITURA DECLARADA — zona X tese Y" em sinais contra-tese a ate 1ATR da zona (independente do read). (4) vela_no_nivel.py = daemon copiloto: cada barra 15M FECHADA nas zonas criticas — toque + pavio minimo 45 pct do range E 0.6xATR + fecho de volta -> alerta imediato (aprox 35s pos-fecho) com grau A (absorcao pela regra de polaridade + regime alinhado) ou B (so assinatura), SL alem do wick +0.15ATR, alvos do mapa/dossie, consulta opcional ao reader; RECALL ALTO POR DESENHO (1a rejeicao dispara, o Cris julga — deliberadamente diferente do R10 que exige 2 rejeicoes: copiloto=recall+descricao honesta, sinal-system=precisao); thresholds FIT calibrados na vela 09:00, rever na 1a semana; Telegram atras de VELA_PRODUCTION_AUTHORIZED (fase 1 chat-only, live so com autorizacao apos 1 sessao). ACEITACAO (accept_mapa_trader_20260804.py) PASS 5/5: vela 09:00 dispara SHORT 4068.28/SL 4073.91; LONG 08:03 marca conflito; 02:00+09:30 nao disparam (location); render sem mapa == golden byte-exato; seccao presente com mapa. Selftests trader_map 5/5 + vela 5/5 + e2 selftest+anchors PASS. e2 kickstarted; vigia 🕯️ armado chat-only. RISCOS monitorados: ancoragem do reader na tese (medir taxa contra-tese no shadow 1 semana), thresholds FIT, fronteira visual copiloto vs E2. Commit e1ac497.',
  array['seed:memory_delta_20260804_copiloto_mapa_vela','copiloto-fase-1-live','mapa-do-trader-trader_map','vela-no-nivel-barra-no-fecho','prefixo-conflito-deterministico','atencao-nao-obediencia','recall-vs-precisao','falha-04-08-long-na-zona-de-venda','aceitacao-dia-real-PASS-5-5','operar-duas-formas'],
  'alert-bridge/trader_map.py+json · vela_no_nivel.py · e2_quality.py · research/accept_mapa_trader_20260804.py · alert-bridge/CLAUDE.md · project_copiloto_mapa_trader · commit e1ac497',
  'active'
)
on conflict (id) do nothing;
commit;
