-- memory_delta_20260719_copilot_journal
-- Feature COPILOT/JOURNAL live (P0-P3, 2026-07-19). Sem secrets, ASCII, sem ponto-e-virgula no texto.
-- ROLLBACK (via SQL Editor): apagar memory_items com a tag deste seed.
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('copilot_journal_live_p0_p3_20260719')::uuid, 'private', 'private', 'architecture',
  'COPILOT/JOURNAL live (P0-P3, 2026-07-19): captura automatica das trades do Cris + journal profundo diario',
  'Convencao canonica: COPILOT = projeto guarda-chuva (copiloto de trading que abrange o live), JOURNAL = 1a feature. Dir copilot/journal/. Diagnostico: o edge comprovado e o Cris (CRIS35 bateu nulls), o sistema AMPLIFICA nao substitui. HOOK de captura provado no chart real via MCP: o Cris marca com a ferramenta Long/Short Position + tag verde Text N (rgba 76,175,80), o draw_list/draw_get_properties leem entry (points) + stopLevel/profitLevel (ticks 0,01) -> entry/SL/TP/dir byte-exato (short 4039 SL 4063,88 TP 3969,20 confirmado). Caveat: draw_list devolve vazio transitorio enquanto edita -> debounce (le 2-3x estavel). P0 captura read-only validada. P1 daemon com.cristrein.copilot-journal-capture (StartInterval 120 + WatchPaths bars_15m): capta tag+posicao -> snapshot 35KB ZERO-CDP (dossie E0 6-axes + TODOS os study_values 15/60/240/1D + latest.json externo completo fed_path/eventos/ouro/news) -> trades.jsonl + sidecar. REVISOES de SL/TP (mantem original = GT no commit). CANCELLED (2 ausencias consecutivas, corrigido para tambem cobrir chart vazio). RESOLVE do RAW (fill quando preco toca entry -> SL-first conservador). P2 daily_journal.py: material do dia + trades + carry-forward N7 -> claude -p Opus (sem ANTHROPIC_API_KEY = Max custo zero) -> entries/AAAA-MM-DD.md + entries.jsonl + lessons.jsonl. Charter DURO: advisory-only NUNCA negoceia/gateia/invalida estrategias aprovadas, ancora nos numeros, ZERO oracle/hindsight, separa decisao-vs-resultado, advogado do diabo, Lisboa. Sample aprovado pelo Cris (recusou inventar intencao do TEST). P3 cron com.cristrein.copilot-journal-daily StartCalendarInterval 22:00 Lisboa (Mac=WEST), start_daily.sh roteia Sab=skip/Dom=weekly/Seg-Sex=diario, weekly_synthesis.py roll-up ISO. Watchdog=21. Read-only, nunca negoceia. Falta so P4 (sync licoes -> Supabase) DEFERIDO. Commits a052a43/77a730e/a349370/0017005/19d0cad.',
  array['seed:memory_delta_20260719_copilot_journal','copilot','journal','captura','claude-p','feature'],
  'memory/project_strategic_reflection_copilot.md e copilot/journal/', 'active')
on conflict (id) do nothing;
