-- memory_delta_20260719_amd_live
-- AMD H4 sweep: backtest (mecanica=breakeven, edge no discricionario) + sinalizacao LIVE F1-F4 EM PRODUCAO.
-- Sem secrets/RAW/params de edge. ASCII. Sem ponto-e-virgula no texto.
-- ROLLBACK (via SQL Editor): apagar memory_items com a tag deste seed.
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('amd_live_signaling_f1_f4_20260719')::uuid, 'private', 'private', 'project',
  'AMD H4 sweep: backtest (mecanica=breakeven, edge no discricionario) + sinalizacao LIVE F1-F4 EM PRODUCAO (human-in-the-loop)',
  'Estrategia AMD/ICT Power-of-3 (2 PDFs): sweep de liquidez PDH/PDL/PWH/PWL numa vela H4 + reclaim no fecho (rejeicao) = Stop Protegido. Entry por FVG 1H retestado. SL abaixo do Order Block 1H sob o FVG (correcao do Cris). Killzone Londres/NY. Bias D1. TP 2R. Wicks=liquidez, corpos=intencao. BACKTEST Fase B (RAW canonico 4H 2013-> + 1H 2024->, DA verificou 4/4 CAUSAL): entrada direta H4 WR 33,8pct N1495 = breakeven. LICAO CHAVE (auditar as proprias medicoes): conclui sem-edge cedo demais sobre medicao com 4 erros que o Cris apanhou (re-sinalizava o mesmo nivel, sweep frouxo, SL no bordo do FVG em vez do OB abaixo, sem filtro de tendencia). Corrigido em amd_v2 (once-per-level + rejeicao close_pos>=0,5 + bias EMA20-D1 + SL abaixo do OB). v2 = ainda breakeven mecanico. CONCLUSAO HONESTA: o edge da AMD vive no DISCRICIONARIO (qual FVG/OB, o PDF chama subjetivo) + gestao, NAO na formula crua. Nao provado sem-edge, provado que a mecanizacao crua e breakeven. SINALIZACAO LIVE = human-in-the-loop EM PRODUCAO (com.cristrein.xau-amd-cycle, WatchPaths raw_4h+raw_1h, watchdog=22). O sistema faz o OBJETIVO (detecao 24/7), o Cris faz o DISCRICIONARIO (qual FVG + entry manual = o edge dele), o journal aprende. F1 Ping-1 SETUP ARMADO (fecho H4 -> Telegram AMD_PRODUCTION_AUTHORIZED). F2 Ping-2 CANDIDATOS FVG/OB 1H (janela 16h, lista todos zona+OB+SL+entry+R+estado). F3 axes.amd_setup no E0 + voz no E2 (advisory NUNCA veto). F4 amd_learn.py junta journal-trades AMD (tag #N amd) <-> setups <-> candidatos -> amd_selection_gt.jsonl (qual FVG ele escolhe), pura medicao, mecanizar so apos N>=30-40 + prereg+forward + gate. Triplo gate anti-flood (once-per-level x dedup persistido x frescura <=1 barra H4): 1o run marcou 254 setups STALE com 0 Telegram. Store-first (REV, zero HD/CDP). Alert-only, nunca negoceia/gateia. Spec docs/architecture/AMD_LIVE_SIGNALING_SPEC.md. Commits d7957bc (F1+F2) e cf7a29d (F3+F4). Codigo amd_lab/amd_v2.py + strategies/xau_amd/amd_live/.',
  array['seed:memory_delta_20260719_amd_live','amd','h4-sweep','live','human-in-the-loop','producao','journal'],
  'memory/project_amd_live_signaling.md e commits d7957bc/cf7a29d', 'active')
on conflict (id) do nothing;
