-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260707_fractal_htf_demand
-- ============================================================================
-- Bloco: fractal MTF vindica Cris; htf_demand_retest = lead causal nao-proxy ambos-anos (promissor-nao-validado) (2026-07-07).
-- ROLLBACK: delete from memory_items where tags @> array['seed:memory_delta_20260707_fractal_htf_demand'];
-- Total: 1 row.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260707_fractal_htf_demand:memory_items:htf-demand-retest-fractal')::uuid,
  'product', 'internal', 'project',
  'Fractal MTF vindica Cris: htf_demand_retest (retest de demanda HTF 4H/1D) = 1o lead causal NAO-proxy que levanta AMBOS anos; promissor-nao-validado (falha so na multiplicidade de selecao)',
  'Cris insistiu (correto): mercado e FRACTAL, a miopia era single-scale. O ms_state 15M separava fase-A(bull-2025) de fase-C(bear-2026) so por CONFOUND DE CALENDARIO/REGIME -> morreu no LOO out-of-fold (0.509<base). Solucao: resample do RAW 15M -> 4H/1D/1W (mtf_kit.py), anti-lookahead rigoroso (barra HTF CORRENTE que contem t EXCLUIDA; so barras fechadas end<=t). Workflow wf_25035e50: 6 familias de features HTF fractais, portao OOF (leave-one-out logistic) + mining-null. 5 falham OOF (fase-4H 0.486, fase-1D 0.515, maturidade-perna-aninhada 0.468, alinhamento-fractal 0.600/p0.155, posicao-room). 1 SOBREVIVE: htf_demand_retest (proximidade/retest de zonas de demanda HTF 4H/1D abaixo do preco + maturidade/posicao de perna) OOF 0.647 (base 0.542), poison 0.73, causal 0/96 violacoes, mining_null_p marginal 0.01. DEVIL ADVOCATE composite mining-null (o teste que apanha winner-curse de SELECAO, obrigatorio pos-ronda-anterior): best-of-6 familias P(best_null>=0.647)=0.08; best-of-13 (6 familias + 7 sinteses) P~=0.14 > 0.10 -> como RESULTADO SELECIONADO in-sample e winner-curse de selecao (o p=0.01 marginal ignora que foi escolhido de ~13 candidatos). MAS o DA CONFIRMA o nucleo, e e o PRIMEIRO lead genuino da sessao: (a) CAUSAL-limpo (grep out=0 nas features, htf_closed_upto exclui barra corrente, 0/96 end>t, sem zona last_t futuro); (b) FRACTAL GENUINO NAO-PROXY -> ablacao: so-demanda 8-feat = 0.667 (melhor que full), so-maturidade/posicao 4-feat = 0.585 (base); reclaim_lag sozinho = 0.527 (<base) e corr<0.14 com todas as features -> NAO e reclaim-R nem regime disfarcado; (c) LEVANTA AMBOS ANOS (DA corrigiu erro do briefing: base-2026 e 46% nao 54.2%): 2025 kept 20/27=74% vs base 63% = +11.1pp; 2026 kept 13/24=54% vs base 46% = +8.2pp (demand-only 2026 +10.5pp); (d) robusto ao threshold (0.60-0.66 em thr 0.45-0.60). VEREDITO = PROMISSOR-NAO-VALIDADO: falha SO na multiplicidade de selecao in-sample, NAO na causalidade/lookahead/proxy. CAMINHO HONESTO (canon sem OOS): pre-registar UMA hipotese unica = demand-only 8-feat, e valida-la em FORWARD/janela virgem (proximos trades live do Cris ou coleta de janela nova) onde o p=0.01 de hipotese-unica passa a ser honesto; qualquer re-selecao in-sample re-incorre a multiplicidade (p~0.14). LICAO DE METODO PERMANENTE: (1) leitura FRACTAL multi-escala e essencial; single-scale confunde-se com calendario; a fase verdadeira le-se por retest de demanda nas escalas HTF, nao no 15M isolado. (2) mining-null tem de ser COMPOSTO (re-correr a selecao de TODAS as familias/configs sobre outcomes embaralhados), nunca single-look de um vencedor. Docs XAU15M_TOTAL_STRUCTURAL_READING_20260707.md; scripts mtf_feat_htf_demand_retest.py, _DA_composite_mining_null.py. commit 8747daf.',
  array['seed:memory_delta_20260707_fractal_htf_demand','fractal-mtf','htf-demand-retest','causal-nao-proxy','promissor-nao-validado','mining-null-composto','prereg-forward','licao-fractal-escala'],
  'docs/architecture/XAU15M_TOTAL_STRUCTURAL_READING_20260707.md; mtf_kit.py + mtf_feat_htf_demand_retest.py + _DA_composite_*.py (workflow wf_25035e50, commit 8747daf)',
  'active'
)
on conflict (id) do nothing;
commit;
