insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('supoe_demais_verificar_nao_assumir')::uuid, 'private', 'private', 'feedback',
  'SUPOE DEMAIS = grande problema recorrente do Claude (Cris 10/08)',
  'SUPOE DEMAIS = o grande problema recorrente do Claude (Cris 2026-08-10, indignado): assumir uma conclusao sem verificar ESTRAGA o sistema. CASO: descartei a polaridade 4350-4362 (ex-supply) so porque o OB Detector removeu a CAIXA do chart — assumi "nivel ido". ERRADO. REGRA: nunca supor uma conclusao, sempre VERIFICAR contra o dado/estrutura real; INDICADOR DEIXAR DE DESENHAR != estrutura desapareceu (caixa OB removida NAO significa que o nivel/zona/polaridade deixou de existir; a polaridade PERMANECE). Antes de dizer "X ja nao existe / foi consumido / esta ido" -> confirmar com os dados, nao assumir. PRINCIPIO estrutural que dai saiu (1a classe): uma SUPPLY rompida COM FORCA vira DEMANDA OBRIGATORIA de ALTA PROBABILIDADE de segurar; sistema/reader leem-na EM 1o LUGAR como suporte de continuacao, mesmo sem a caixa OB. Relaciona feedback_never_invent_read_existing_indicator, feedback_no_superficial_hasty_reading.',
  array['seed:memory_delta_polarity_20260810','supoe-demais','verificar-nao-assumir','caixa-removida-nao-e-nivel-ido','polaridade'],
  'memory/feedback_supoe_demais_verificar_nao_assumir.md', 'active'),
 (md5('polarity_tracker_live')::uuid, 'private', 'private', 'project',
  'Polaridade persistente LIVE + lei validada +12pp (2026-08-10)',
  'POLARIDADE PERSISTENTE LIVE 10/08 (autonomia 2h Cris). LEI: supply furada com forca vira demanda obrigatoria — VALIDADA A SERIO (nao assumida). polarity_hold_study_v2 com fixes do Devil-s Advocate: (1) NULL emparelhado (nivel aleatorio, mesma def), (2) geometria congelada em born_t, (3) definicao SIMETRICA por fecho (v1 = pavio-hold vs fecho-fail = enviesado -> inflava 67%), (4) forca via leg_v3 IMPULSO (existente, sem threshold inventado). RESULTADO: ex-SUPPLY furada COM FORCA segura 64% vs NULL 52% = +12pp MATERIAL (n=1038); todos os rompimentos 62% vs 52% = +9.7pp; ex-DEMAND 60% vs 48% = +12.3pp; ex-DEMAND com forca 73% vs 45% = +28.7pp mas n=135 fraca. v1 dizia 67% mas o null era 64% (so +2.7pp) = artefato pavio/fecho que o DA apanhou; corrigido = +12pp real. IMPLEMENTACAO: polarity_tracker.py cataloga supplies/demands vistos (tipo real via ob_watch._read_ob) -> regista polaridade quando o preco FURA (fecho real vs fronteira real) -> PERSISTE independente da caixa OB (o defeito que o Cris apontou: caixa removida != nivel ido) -> invalida no fecho alem por D=1.0ATR (distancia validada). Single-writer candle_reader.update() 1x/ciclo. Catalogo sobrevive a caixa sumir. WIRE: ob_watch.load_ob_zones inclui polaridades persistentes (vela+validador vigiam) + candle_reader prompt bloco POLARIDADES ATIVAS + TAPE_SYS principio "supply furada c/ forca = suporte obrigatorio, le em 1o lugar" (forca = discricao do reader). So FACTOS: OB tipo real + fechos reais + leg_v3, nada inventado. Selftests PASS, integracao verificada, daemons reiniciados, commit+push. Flags POLARITY_OFF/POLARITY_NEAR_PTS.',
  array['seed:memory_delta_polarity_20260810','polaridade','lei-validada','tracker-persistente','ex-supply-demanda','reader','ob-watch','live'],
  'memory/project_polarity_tracker_live.md', 'active')
on conflict (id) do nothing;
