-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260804_amd_audit_and_voice_decision
-- ============================================================================
-- Auditoria+estudo AMD (DA reprovou features) + governanca voz-propria/Cris-filtra. 2 rows. Idempotente.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260804_amd_audit_and_voice_decision:memory_items:amd')::uuid,
  'product', 'internal', 'project',
  'AUDITORIA + ESTUDO AMD H4 (2026-08-04): 3 sinais live = 0W/2L-shorts/1 no-fill = breakeven; estudo de features N=51 REPROVADO pelo Devil''s Advocate; AMD mecanico = breakeven, nenhuma feature confiavel; melhoria defensavel = candidato AMD via eixo de liquidez + reader no Ping-2 (LEITURA nao gate), forward = unico arbitro',
  'AUDITORIA dos 3 sinais AMD H4 LIVE (go-live 19/07; os outros 254 do ledger = backfill 2020->2026, nunca sinais): Caso1 20/07 SHORT@4020 = LOSS (encheu, +0.76R, reverteu e stopou, depois +160pts contra ate 4166 -> shortou um fundo/bear-trap); Caso2 31/07 LONG@4028 = SEM TRADE (Ping-1 disparou, nenhum candidato 1H retestado, tese lateral; triplo-gate anti-flood funcionou); Caso3 04/08 SHORT@4072 = LOSS (encheu 4055.5, +0.27R, reclaim genuino through SL ate 4093). PLACAR LIVE 0W/2L/1no-fill. Fio comum = AMD shorts a apanhar REVERSOES (le mecanica H4 sweep+reclaim mas NAO discrimina trap vs genuino). ESTUDO de features (research/amd_feature_separation_study_20260804.py) N=51 mecanico: global WR35%/avgR+0.06 = breakeven confirmado. Separacao estrela range-meio (+0.59R/53%) REPROVADA pelo DA em 4 frentes: (1) multiplicidade p=0.075 sem correcao, Bonferroni exigia <=0.003 (1 ordem de grandeza fora, dentro do "1 spurious por acaso" que o script previu, ~18 buckets); (2) poder N=17 IC Wilson [31%,74%] atravessa breakeven; (3) ARTEFATO INTRABAR grave: resolvedor decide fill+alvo na mesma barra 1H sem ordem intrabar, 5 "wins" abrem ja alem do alvo (gap) e fecham abaixo = falsos, corrigido WR 35->25% range-meio 53->41% (mesma forma do desastre A1 Supertrend 88->46%); (4) regime degenerado: os 51 sao TODOS bias_layer1=BEAR (artefato de backfill), zero fora-de-regime. Proxy de entry (nivel) != live (FVG-retest); no-fill enviesado por direcao (shorts -46%). VEREDITO: AMD mecanico ~= breakeven, NENHUMA feature confiavel para informar design. DIRECAO DE MELHORIA DEFENSAVEL (causal, nao mined; mantendo logica base sweep+reclaim H4 killzone): NAO novo gate mecanico. Enriquecer a LEITURA no Ping-2 com o que discrimina trap vs genuino ja construido hoje: eixo de liquidez (INICIATIVA_PARA_IMAN vs DESLOCAMENTO_POS_SWEEP; teria marcado caso3 como CONTRA) + posicao estrutural + submeter candidato AMD ao reader E2. AMD = onde olhar (Ping-1); entrar = convergencia de leitura (Ping-2). PRE-REQUISITOS DO DA antes de crer em qualquer numero AMD futuro: corrigir resolucao intrabar (alvo DEPOIS do fill ou barras 15M/5M), resolucao FVG-exata, multi-regime (impossivel com backfill todo-BEAR). Desenho Plan do wiring Ping-2 pronto (hook run_amd_cycle.py bloco F2, candidato -> run_read, veredito CONVERGE/CONTRA/NEUTRO de liquidez+reader como LINHA no Telegram, backtest historico NAO credivel = forward-only shadow com metrica unica pre-registada). NAO implementado (aguarda autorizacao).',
  array['seed:memory_delta_20260804_amd_audit_and_voice_decision','auditoria-amd-h4','3-sinais-live-0W-2L-1nofill-breakeven','estudo-features-reprovado-DA','multiplicidade-p0075','artefato-intrabar-35-25wr','regime-todo-bear-degenerado','amd-mecanico-breakeven','melhoria-ping2-via-liquidez-reader','leitura-nao-gate','forward-unico-arbitro'],
  'research/amd_feature_separation_study_20260804.py · project_amd_audit_and_feature_study · .amd_state/amd_setups.jsonl · Plan design Ping-2',
  'active'
),
(
  md5('seed:memory_delta_20260804_amd_audit_and_voice_decision:memory_items:voice')::uuid,
  'product', 'internal', 'decision',
  'GOVERNANCA (Cris 2026-08-04, apos dia -4R em que o sistema o induziu ao erro): sistema mantem VOZ PROPRIA (pode discordar da tese do Cris) e o CRIS FILTRA — escolhido sobre "estritamente subordinado"; vozes/conflito/liquidez = AVISOS nunca vetos; mas sinal contra tese declarada exige conviccao extraordinaria + conflito explicito',
  'CONTEXTO: dia real -4R (~450 USD) em que o sistema no liquido PIOROU o dia do Cris — induziu-o a um LONG no topo (4063, dentro da zona de venda declarada) e depois recusou o reclaim genuino das 11:30 (a compra certa, +3R perdidos). A leitura do Cris estava CERTA desde a abertura; a ajuda do sistema subtraiu. Perguntado explicitamente entre (A) sistema estritamente subordinado ao plano declarado (so confirma ou cala, nunca surfa contra a tese) e (B) sistema mantem voz propria podendo discordar e o Cris filtra -> Cris ESCOLHEU B. WHY: o edge comprovado e o Cris, mas ele quer a informacao independente da maquina, nao um eco; prefere ver a discordancia e decidir a ter a maquina amordacada. HOW TO APPLY: manter as vozes como estao (mapa do trader = atencao-nao-obediencia; prefixo de CONFLITO e eixo de liquidez = avisos/vozes NUNCA vetos nem ordens; o reader pode surfar contra a tese SE a fita mandar, com conflito declarado por extenso) — ISTO JA E A CONFIG LIVE, nao subordinar nao amordacar; o Cris e o arbitro final de cada sinal. MAS a barra de hoje mantem-se: sinal contra a tese declarada exige conviccao EXTRAORDINARIA + conflito explicito (nunca um sinal "limpo" contra o plano — foi esse o erro das 08:03). Voz propria != voz descuidada. Consequencia pratica: NADA a mudar no comportamento (a escolha do Cris coincide com o sistema atual); o ganho de hoje foi mais informacao na voz (conflito+liquidez), nao menos autonomia dele.',
  array['seed:memory_delta_20260804_amd_audit_and_voice_decision','governanca-voz-propria-cris-filtra','dia-menos-4R-sistema-piorou','escolha-B-voz-propria-vs-subordinado','vozes-sao-avisos-nunca-vetos','sinal-contra-tese-exige-conviccao-extraordinaria','config-live-ja-coincide','cris-arbitro-final'],
  'feedback_system_voice_cris_filters · project_copiloto_mapa_trader · project_liquidity_axis_e0_e2',
  'active'
)
on conflict (id) do nothing;
commit;
