-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260727_retoma_engine
-- ============================================================================
-- Gap #2: RETOMA ENGINE v1 (higher-low em demanda) — caracterizacao + prereg + coletor forward dry.
-- Aplicar via scripts/supabase/apply_memory_delta.py. Idempotente. Total: 1 row.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260727_retoma_engine:memory_items:retoma-engine-v1')::uuid,
  'product', 'internal', 'project',
  'RETOMA ENGINE v1 (gap #2, Cris 2026-07-27): camada higher-low-em-demanda selada — prereg congelado + coletor forward DRY no router BEAR; Cp intocado; DA apanhou circularidade retro nas zonas',
  'CARACTERIZACAO (research/cp_char_fresh_bottoms_20260727.py): os 4 fundos ideais do Cris (A 16/07 3969 · B 20/07 3998 · C 24/07 4044 · D hoje 4065, fontes verificadas store==buffer-Cp 85=85 bubbles) medidos com os gates VERBATIM do Cp -> ZERO passa e cada um falha um MIX diferente (nao ha limiar unico para afinar); 3/4 sao HIGHER-LOWS de retoma (nao capitulacoes: Cp exige low absoluto de 2 dias + perna >=15xATR + leilao intenso; GT profundo = 18-32x/act 0,82); TODOS tem reclaim (entry_first dispara nos 4) -> a mecanica de entrada serve, falha a QUALIFICACAO. Classe estruturalmente DISTINTA -> engine proprio, Cp congelado INTOCADO (baixar limiares esmagaria 2 classes e partia o baseline). GAP REAL = camada orfa no router: em macro-BEAR so o Cp vigia; retoma-de-demanda nao tinha dono. MOTOR (my-strategy/research/revalidation/retoma_engine_v1.py, funcoes puras, consome cp_engine_live verbatim): fractal M=3 + legMag>=8xATR (PRINCIPIO metade-do-canonico-Cp, nao re-derivado dos GT) + COMPLEMENTO do Cp por construcao (fundo_ok==None -> zero overlap de alertas) + ANCORAGEM em demanda EXISTENTE do store <=0.5ATR (licao S1) + reclaim verbatim + SL=min(zona.low, low)-0.1ATR (padrao SLs estruturais do Cris 3997.55x3) + 3R fixo; leilao = voz nunca veto. DA LOOKAHEAD (escopo estrito): caminho preco->entrada->outcome LIMPO; ACHADO MATERIAL = CIRCULARIDADE RETRO: zonas do store sao snapshot sem data de criacao e em B/C/D zona.low==low do proprio fundo -> a validacao retroativa da ancoragem valida-se a si propria -> painel in-sample (N44 WR41% +28R vs null 24%) e GT 4/4 REBAIXADOS a caracterizacao direcional, NUNCA evidencia de edge; null tambem usava SL diferente (nao comparavel). RESPOSTA CANONICA: forward LIMPO POR CONSTRUCAO — coletor no ramo BEAR do router (run_retoma, ciclo 900s DRY, 0 Telegram): zonas AS-OF do ciclo GRAVADAS no registo (zona_asof, auditavel), SO regista candidato com entrada fresca <=2 barras (o passado nunca e varrido com zonas de hoje), ledger .router_state/retoma_ledger.jsonl dedup por fundo_t + resolve SL-first. PREREG CONGELADO docs/architecture/RETOMA_ENGINE_V1_PREREG_FORWARD_20260727.md: PASS = N>=20 resolved forward · hit-3R>=45% · streak<=5 · exp>0 · bate null mesmo-SL; so depois decisao Cris sobre Telegram (RETOMA_PRODUCTION_AUTHORIZED). Invalidacao declarada: se higher-lows em bear = facas (WR<<null), a camada morre — nao se afina ao resultado. 1o ciclo live OK: BEAR -> 5 cands janela, 0 frescos (sem backfill retro). Router e StartInterval (pega codigo novo sozinho).',
  array['seed:memory_delta_20260727_retoma_engine','retoma-engine','higher-low','camada-orfa-router','cp-intocado','complemento-do-cp','ancoragem-demanda','sl-estrutural','da-circularidade-zonas','forward-limpo-por-construcao','prereg-congelado','dry','user-approved'],
  'my-strategy/research/revalidation/retoma_engine_v1.py · retoma_study_20260727.py · research/cp_char_fresh_bottoms_20260727.py · ENTRY_ROUTER/run_router_cycle.py::run_retoma · docs/architecture/RETOMA_ENGINE_V1_PREREG_FORWARD_20260727.md',
  'active'
)
on conflict (id) do nothing;
commit;
