-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260804_vela_fixes_day_lessons
-- ============================================================================
-- Fixes vela-no-nivel (zona/1H/35%) + licoes do dia -4R + mapa gatilho 4074.44. 2 rows. Idempotente.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260804_vela_fixes_day_lessons:memory_items:lesson')::uuid,
  'product', 'internal', 'feedback',
  'REINCIDENCIA GRAVE (Cris 2026-08-04, dia -4R): inventei a regua de rejeicao da vela-no-nivel em vez de LER o OB Detector/SMC/Bubbles que ja estao no chart — um short real falhou por 0.36pt de uma regua que nem devia existir; SEMPRE ler o indicador existente, a ZONA (OB Detector) e o filtro nao a aritmetica inventada',
  'PECADO REINCIDENTE (documentado em feedback_never_invent_read_existing_indicator): construi a assinatura da vela-no-nivel em thresholds INVENTADOS por mim — pavio >=45% do range, "fecho na metade inferior da vela", multiplos de ATR — em vez de LER os indicadores que ja estao no chart do Cris (OB Detector v11 = zonas, SMC = rejeicao/BOS/CHoCH, Market Order Bubbles = absorcao, NAS = exaustao, SVP). CUSTO REAL: a vela 15M das 18:00 (04/08) entrou na premium 4101-4116, pavio 47%, fechou 4099.85 ABAIXO da zona = rejeicao de manual — mas foi rejeitada por 0.36pt pela minha regra que media a geometria interna da vela (fecho vs meio dela propria) em vez de medir contra a ZONA. Cris: "que medicao de merda e essa? da onde inventaste? de novo? inventas o que nao peco mais uma vez?". OS DOIS FUROS DO DIA (ambos meus): (1) regua inventada (geometria da vela) rejeitou short real por 0.36pt; (2) vigia so em 15M -> CEGA ao 1H, onde a rejeicao das 18:00 foi mais clara (fechou 4086 no low, 64% pavio = o sinal mais claro do dia). CORRECOES APLICADAS (paliativas — a regua ainda e minha, nao o indicador): (a) rejeicao baseada na ZONA (dispara se fecha de volta ABAIXO da supply OU metade inferior, nao a geometria); (b) estendida a 1H (scan_zones corre 15M+1H agregado 4x15m ATR proprio, dedup por (tf,zona); 5M fora=ruido ordem Cris); (c) threshold pavio 45%->35% + piso ATR 0.6->0.3 (Cris "qualquer pavio 35-50% vale EM regiao OB"; a zona OB e o filtro de ruido nao o tamanho do pavio). selftest 8/8 (1H 18:00 dispara + pavio 37.5% dispara + doji bloqueado). HOW TO APPLY PERMANENTE: antes de inventar QUALQUER medicao de rejeicao/absorcao/exaustao/zona -> LER o indicador que ja a computa (store/pine_boxes/study_values). PENDENTE: reescrever a vela para LER o OB Detector diretamente (Cris aprovou direcao, nao feito). CONTEXTO DO DIA: -4R (~450 USD), sistema NET-NEGATIVO, a leitura discricionaria do Cris esteve CERTA o dia todo (topo, rejeicao, nivel, continuacao); o edge e o Cris, o sistema falhou em confirmar a tempo.',
  array['seed:memory_delta_20260804_vela_fixes_day_lessons','ler-ob-detector-nao-inventar-threshold','reincidencia-inventar-medicao','short-perdido-por-0.36pt','vela-cega-ao-1h-furo2','rejeicao-baseada-na-zona','vela-estendida-1h','pavio-45-para-35','dia-menos-4R-sistema-net-negativo','edge-e-o-cris'],
  'alert-bridge/vela_no_nivel.py · feedback_read_ob_detector_not_invent_thresholds · feedback_never_invent_read_existing_indicator · project_copiloto_mapa_trader',
  'active'
),
(
  md5('seed:memory_delta_20260804_vela_fixes_day_lessons:memory_items:mapa')::uuid,
  'product', 'internal', 'project',
  'Mapa do trader + vela-no-nivel estado 2026-08-04 fim-do-dia: 6 zonas (5 SHORT + 1 LONG) + nivel-gatilho 4074.44 (fecho abaixo = reversao SHORT confirmada, tese Cris); vela vigia 15M+1H com pavio 35%; lag do reader corrigido (liquidez/agressao frescas do store)',
  'MAPA DO TRADER ATIVO (fim do dia 04/08): supply 4066-4073 SHORT · OB 15M 4099-4106 SHORT (zona de PULLBACK pos-dive) · micro 4088-4091 SHORT (pullback RASO, Cris "e se nao passar de 4090") · OB premium 4101-4116 SHORT · OB 4H 4138-4166 SHORT · demand 4H 3995-4011 LONG. NIVEL-GATILHO tese_geral: 4074.44 = fecho decisivo ABAIXO = REVERSAO SHORT CONFIRMADA (tese Cris, "nao e menor probabilidade, e o gatilho"); reader factoriza em cada read. VELA-NO-NIVEL vigia as zonas em 15M E 1H (pavio >=35%, rejeicao-por-zona). LAG DO READER CORRIGIDO (e2_quality render_composite recalcula read_confluence_store + read_liquidity do bar-store NO INSTANTE do read, gate _live_read; o dossie chegava ~1 ciclo atrasado e atrasava pontos de entrada; commit 2cf2e6d). READER DE VELA CONSTANTE com read imediato no arranque. MONITORING afinado: acordar so na rejeicao de zona, nao em cada leitura de rotina (era ruido); confirmados vao ao Telegram. CENARIO DO CRIS no fim do dia: bear, preco dived da premium 4106 ate ~4076, pullback a comecar ~4080; plano = short na rejeicao de uma zona (4088-91/4099-4106/4101-4116) OU reversao confirmada se fechar <4074.44; possivel bounce LONG se segurar demand 4066-4073+reclaim (venda absorvida no OB abaixo, lows a reclamar). Cris acompanha o pullback, avisa-se na rejeicao.',
  array['seed:memory_delta_20260804_vela_fixes_day_lessons','mapa-6-zonas-5short-1long','nivel-gatilho-4074.44-reversao-confirmada','vela-vigia-15m-e-1h-pavio-35','zonas-pullback-4088-4099-4101','lag-reader-corrigido-2cf2e6d','monitoring-so-rejeicao','pullback-a-comecar-4080'],
  'alert-bridge/trader_map.json · vela_no_nivel.py · e2_quality.py · candle_reader.py · project_copiloto_mapa_trader · project_candle_reader_constant',
  'active'
)
on conflict (id) do nothing;
commit;
