-- memory_delta_20260720_shock_v3_and_4040
-- Price-shock v3 (deteccao por excursao) + caso forward 4040 (SHORT 2R que o sistema tinha e nao validou).
-- Sem secrets/RAW/params de edge. ASCII. Sem ponto-e-virgula no texto.
-- ROLLBACK (via SQL Editor): apagar memory_items com a tag deste seed.
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('price_shock_v3_excursion_20260720')::uuid, 'private', 'private', 'feedback',
  'Price-shock v3: detecao por EXCURSAO high/low (apanha wicks), pontos absolutos >=10/>=18',
  'Feedback Cris: uma queda forte real (wick 5M a 4001, -11pt intra-bar que recuperou a 4009) NAO foi sinalizada. Root cause DUPLO: (1) close-to-close e cego a wicks (via so -3, a excursao ve -11); (2) threshold ATR15 alto demais. FIX v3 (commit 469dc53): detect_excursion mede a maior excursao rapida via HIGH/LOW da barra 5M vs close anterior (<=5min), em PONTOS ABSOLUTOS: choque>=10pts, major>=18. Medir por high/low e o cerne (apanha wicks que recuperam). Absoluto nao ATR (o trader sente pontos). PROVADO nos dados reais de hoje: apanha 4/132 barras (spike 4040 +18, wick 4001 -11, +2 de 10-13pts) e ignora 95% normais (range<8) = sem zigzag. Le a tab 5M (granularidade p/ wicks). JORNADA de calibracao no mesmo dia (mercado real como professor): ATR5 close-to-close=zigzag spam -> ATR15 close-to-close=perdia wicks -> EXCURSAO high/low absoluta=apanha o real ignora ruido. FILOSOFIA do Cris: a medida que o mercado real acontece aprendemos e ajustamos parametros ancorados em dados nao palpite. Tambem news_escalate: lexico de DE-ESCALACAO (ceasefire/truce/deal=BEARISH XAU) - a causa da queda de hoje (cessar-fogo Irao-EUA tira premio safe-haven) que o classificador perdia. Guard tab-missing (bar-store alerta instantaneo <=60s) e tab_pin read-only (nao canibaliza) tambem nesta sessao.',
  array['seed:memory_delta_20260720_shock_v3_and_4040','price-shock','excursao','wicks','news-bearish','calibracao'],
  'memory feedback_price_shock_real_not_zigzag + commit 469dc53', 'active'),
 (md5('short_engine_4040_forward_case_20260720')::uuid, 'private', 'private', 'project',
  'Caso forward 4040 (2026-07-20): SHORT 2R que funcionou e o sistema TINHA mas nao validou - requisito do engine SHORT',
  'O XAU fez spike a 4040 (news), rejeitou, e um SHORT nessa rejeicao foi um 2R que FUNCIONOU (Cris viu no grafico e operou). O sistema live NAO o sinalizou - auditoria do funil E1/E2 do dia. (1) Nenhum candidato foi gerado no spike 4040: sweep_reclaim ancora em varrer um topo de swing PRE-EXISTENTE (grab de liquidez de nivel conhecido) e 4040 era topo NOVO movido por news (nao varreu nada) - zone_reject exige zona de oferta PRE-DEFINIDA em 4040 (nao havia) - a rejeicao do spike nao bate com nenhuma das 2 regras atuais. (2) Setups SHORT proximos falharam o gate >=2R: 09:45 (1.49R) e 11:46 (1.29R) porque a entrada do sistema e ~4022 (meio da faixa) nao na rejeicao - a entrada do Cris foi na rejeicao ~4030-4035 colada ao 4040 com SL apertado acima de 4041 = 2R (mesma direcao entrada muito melhor). (3) Causa-raiz: entrada close-only (fecho da barra 15M) e estruturalmente TARDIA num spike rapido - quando a barra fechou ~4022 o spike ja desvaneceu 18pts e a geometria colapsa para <2R. (4) O que passou no E1 (09:01 3R) foi vetado por chase no E2. REQUISITO do engine SHORT (confirma o discriminador teste-e-rejeicao no iman): regra que dispara na TESTE-E-REJEICAO no iman superior (BB 15M + SVP + spike fresco) ancorada no iman e no PRECO da rejeicao - nao so sweep de topo previo e nao entrada no fecho tardio. A ferramenta de captura ja existe: o BB-watch/zone-watch (price-shock desta sessao) teria alertado em tempo real ao tocar 4031-4041 (o ponto de entrada do Cris) - falta o auto-sinal com essa ancora. Estes sinais eram preciosos e tinhamo-los no sistema so nao os validamos. Prioridade do dev SHORT desta semana.',
  array['seed:memory_delta_20260720_shock_v3_and_4040','short','engine','4040','forward-case','iman','teste-rejeicao'],
  'memory project_xau_short_engine_dev_20260720', 'active')
on conflict (id) do nothing;
