insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('fvg_confluence_entry_method')::uuid, 'private', 'private', 'reference',
  'Metodo FVG-confluencia para entry de compra (Cris 10/08)',
  'DESCOBERTA Cris 10/08: buscar FVGs (Fair Value Gaps) inferiores nao-preenchidos em 5M+15M+30M+1H sobrepostos a demanda estrutural = melhores pontos de entry. O fill do gap da localizacao PRECISA, corrige o problema recorrente de "sempre atras do preco" (chase). Quando o mesmo FVG aparece em varios timeframes E coincide com demanda = entrada de alta qualidade. REGRA (integra pacto): comprar SO com rejeicao impressa na zona (vela-no-nivel + reader confirmam), nunca a faca; size 1%, SL abaixo do FVG, deixar correr ao alvo (nao fechar cedo); reentrada so quando o sistema sinaliza. ZONAS marcadas 10/08 no trader_map.json (preco ~4358): buy_fvg_deep_4298_4303 = PRIMARIA (preferida do Cris, fill profundo, tripla FVG 15M+30M+1H + demanda 4301-10, SL ~4290, melhor RR, alvo 4337->4358->novos maximos); buy_fvg_4337_4341 = rasa (FVG triplo + demanda, SL apertado; 10/08 tocada mas reader refutou GO a 4347 = chase no topo RR 0.4, filtrado corretamente). CONTAS 10/08: FTMO +2.15% (de -1.2%), FN -2.7%/$97.250 (de -4.54%), ambas FLAT (Cris fechou tudo 09/08 com +1.56%). Objetivo: passar os 2 challenges ate fim de agosto.',
  array['seed:memory_delta_fvg_earlyclose_20260810','fvg','confluencia','entry','multi-timeframe','reentrada','zonas'],
  'memory/reference_fvg_confluence_entry_method.md', 'active'),
 (md5('cris_early_close_fear_pattern')::uuid, 'private', 'private', 'feedback',
  'Padrao de fecho-cedo por medo - CONFIRMADO pelo Cris (10/08)',
  'PADRAO COMPORTAMENTAL confirmado verbatim pelo Cris 10/08: "e meu padrao de fechar cedo, nada ainda demonstra perda de estrutura inclusive em 5M, ja estaria agora com 1.800 de lucro. mais uma vez medo me domina." O TRADE: entrou LONG via FVG (limit 4315 SL 4299), acordou a +1.56%, FECHOU tudo antes de a tese completar; preco continuou a favor (teria ~+1.800 vs o garantido), sem qualquer perda de estrutura nem em 5M. E o MESMO motor do shortar-o-topo: ansiedade sob P&L. MATEMATICA: fechar a +1.5% em vez de correr ao alvo 3R obriga a MAIS trades para recuperar -2.7% FN; a regra "deixar correr" existe para 2-3 winners chegarem. CONTRATO DE ESPELHO (o que o Claude DEVE fazer): questionar TODA vontade de fechar um long a meio sem ser SL/alvo - "a estrutura mudou de facto? em 5M sequer imprimiu perda? se nao, a tua regra e deixar correr". Nao e forcar a segurar cegamente - e obrigar a nomear a razao REAL; se e medo e nao estrutura, e o padrao a corrigir. Reforca regra no3 do pacto de disciplina 07/08 (NUNCA fechar exceto SL/alvo).',
  array['seed:memory_delta_fvg_earlyclose_20260810','fecho-cedo','medo','disciplina','pacto','contrato-espelho'],
  'memory/feedback_cris_early_close_fear_pattern.md', 'active')
on conflict (id) do nothing;
