-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260803_shorts_audit_read_nuances
-- ============================================================================
-- Auditoria shorts recusados (DA-corrigida) + blocos FADE-SEQUENCIA e COMPRESSAO no READ_SYS. 1 row.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260803_shorts_audit_read_nuances:memory_items:fix')::uuid,
  'product', 'internal', 'feedback',
  'Auditoria SHORTs recusados (DA-corrigida: reader break-even N=16, nao negativo) + blocos FADE-EM-SUPPLY-COM-SEQUENCIA e CONTINUACAO-EM-COMPRESSAO no READ_SYS (check anti-reabertura 0/13) — Cris 2026-08-03',
  'GATILHO: SHORT 4061.65 recusado 03/08 08:16 por "auction sem agressao + ADX morto" correu +42pts (MFE 2.27R, MAE 0.16R) sem tocar o stop — Cris: "foi uma perda clara e desnecessaria"; e corrigiu-me o "corretamente recusado" = LICAO: nunca declarar recusa correta sem VERIFICAR contra o preco. AUDITORIA (matriz de confusao 24 recusas 26/07-03/08) + DA CLEAN-WITH-CAVEATS com correcoes materiais: 6 das 24 eram kills do gate bad_rr (reader nunca viu, incl. 1 "winner" mal-atribuido), 2 pares duplicados; READER-ONLY DEDUP = 3 recusas erradas genuinas (-10.4R; incl. 4106 knife-edge a 2.87pts do SL) vs 13 certas (+13R) = BREAK-EVEN N=16; pipeline dedup +2.7R pro-recusa. Conclusao "conservadoria custa mais do que protege" NAO suportada, entao afinacao CIRURGICA, nunca loosening. DOIS PADROES nos erros: (a) fade em supply com sequencia morto por "com-perna sem exaustao HTF" mesmo quando a leitura VIU a tensao rotulo-vs-dados-1H; (b) continuacao com-perna recusada por exigir agressao vendedora PRE-quebra — em COMPRESSAO nas EMAs a agressao imprime DEPOIS do rompimento (ADX morto+CHOP = estado ESPERADO da pre-quebra). FIX (2 blocos READ_SYS, e2_quality.py): A) FADE EM SUPPLY COM SEQUENCIA: sweep do TOPO + minimo 2 rejeicoes confirmadas na supply 4H/1D + lower-high a segurar = voz forte MESMO sem CHoCH 15M QUANDO o rotulo da perna 1H contradiz os dados 1H (rotulo = dado atrasado); B) CONTINUACAO EM COMPRESSAO: com-perna em compressao nas EMAs nao exige agressao previa nem ADX vivo; distinguir AUSENCIA de agressao (aceitavel) de AGRESSAO CONTRARIA ativa (veto pleno); guardas so-com-perna + fora de eventos + espaco/alvo pesa normal. PROTOCOLO CUMPRIDO (ordem Cris): DA primeiro, desenho, e CHECK ANTI-REABERTURA ANTES de implementar: classificador deterministico sobre as 13 recusas-certas = 0/13 casam com A/B (zero risco de reabrir os losers evitados; as 13 tinham agressao compradora ativa ou frame/dados de acordo = discriminadores reais nos dados). 4 sondas Opus: P1 faca recusada 2/2, P4 guarda buy-aggr recusada 2/2 (seguranca consistente), P2 fade-sequencia SURFACED conv 62-63 2/2 (robusto), P3 compressao borderline (surfaced 1/2, conv 37-38) = FORWARD WATCH. selftest+anchors PASS; e2 kickstarted; rollback = revert do commit 20c36c2. Scripts reproduziveis: audit_refused_shorts_20260803, probe_loser_reopen_check_20260803, probe_short_nuances_20260803.',
  array['seed:memory_delta_20260803_shorts_audit_read_nuances','shorts-recusados-break-even-N16','DA-corrigiu-duplicados-e-atribuicao','nunca-declarar-correto-sem-verificar','fade-supply-com-sequencia','continuacao-em-compressao','ausencia-vs-agressao-contraria','check-anti-reabertura-0-de-13','P3-borderline-forward-watch','rotulo-dado-atrasado'],
  'alert-bridge/e2_quality.py (READ_SYS blocos A+B) · research/audit_refused_shorts_20260803.py · probe_loser_reopen_check_20260803.py · probe_short_nuances_20260803.py · feedback_leg_label_lags_at_turns · commit 20c36c2',
  'active'
)
on conflict (id) do nothing;
commit;
