begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260804_live_review_fixes:memory_items:review')::uuid,
  'product','internal','decision',
  'REVISAO TOTAL DO LIVE (Cris 2026-08-04 "deixa o live perfeito"): agente de code-review achou 23 findings; CRITICOS corrigidos na hora — candle_reader lia 1 VELA ATRASADO (bars[-2]; store so escreve fechadas), starvation 15M/1H (30x5M/3x15M/0x1H lidos), vela 1H scan MORTO (ATR None), SVP/Volume None por narrow-nbsp, dedup Telegram entre daemons',
  'AUDITORIA DE CODIGO completa (agente DA-style) dos daemons live. CRITICOS CORRIGIDOS: (1) candle_reader bars[-2] = 1 vela atrasado permanente (o bar_store_cycle NUNCA escreve a vela em formacao -> [-1] E a ultima fechada; evidencia: reads 654-709s apos open) -> [-1] em todo lado; (2) freshest-first cross-TF marcava TFs como lidos SEM os ler (evidencia live: 33 reads = 30x5M/3x15M/0x1H — os TFs que importam eram os saltados) -> prioridade 60>15>5 + marca SO o TF lido com o t lido; (3) vela 1H scan DOA: load_bars n=40 -> 10 horas -> atr14 exige 15 -> None -> decide None (a rejeicao 1H das 18:00, razao de existir do 1H, nunca poderia disparar; selftest passava porque injeta ATR) -> n=80/budget 30000 = 19h ATR 18.4 OK; (4) _num nao tirava narrow-nbsp (\\u202f) dos valores TV -> SVP/Volume sempre None e read_line dizia "SVP comprador" FALSO no prompt do Opus -> strip + "SVP —" quando ausente; (5) 3 daemons com TG ON = 2-4 alertas duplicados por evento (vela+validador mesma condicao decide()) + zonas sobrepostas 4088-91/4090-4106/4099-4106/4101-16 = tempestade no reteste planeado -> tg_claim lockfile O_EXCL por (classe_evento, t da vela), 1 dono por evento, fail-open; (6) consult do reader bloqueava a vigia ate 15min por alerta -> 1 consult/vela timeout 90s; (7) candle_reader crashava sem dossie + 1H aceitava hora parcial -> guards. MEDIA: criticidade movida decide()->scan_zones (validador pode GO em zona nao-critica); validador 1H ATR proprio; _tg limpo; snapshot atomico os.replace; context_liquidity sweep index re-avalia barra j. MORTO REMOVIDO: ob_zones.py (3 leitores OB paralelos na mesma noite — consolidado em market_read). PENDENTES (nao-bloqueantes, anotados): restart amnesia (fired/seen em memoria -> dup pos-restart), logs sem rotacao (candle_reads/e1_candidates), saturacao Opus pelo 5M (ordem explicita Cris opcao B — manter), TAPE_SCHEMA literal false, sessao asia_lo cross-midnight no context_liquidity. CLEARED: sem circular imports, sem races (tmp+os.replace em todo o store), _live_read gate ok, e2 offsets ok. Selftests todos PASS; 3 daemons recarregados na reabertura da Asia.',
  array['seed:memory_delta_20260804_live_review_fixes','code-review-23-findings','candle-reader-1-vela-atrasado-fix','starvation-15m-1h-fix','vela-1h-scan-morto-fix','svp-narrow-nbsp-fix','tg-claim-dedup-1-dono-por-evento','consult-cap-90s','ob_zones-morto-removido','pendentes-anotados-restart-amnesia-log-rotation'],
  'alert-bridge/{candle_reader,vela_no_nivel,entry_validator,market_read,context_liquidity}.py · review agent findings · commit da revisao',
  'active'
)
on conflict (id) do nothing;
commit;
