-- memory_delta_20260719_regime_consolidation_audit
-- Arco de regime 2026-07-19: DXY live + Layer1 autoridade + E0/E2 vozes + consolidacao + router dry +
-- auditoria v5-4H (decisao A) + feedback consolidar-nao-proliferar. Sem secrets/RAW/params de edge. ASCII.
-- ROLLBACK: delete from memory_items where tags @> array['seed:memory_delta_20260719_regime_consolidation_audit'];
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status)
values
 (md5('regime_consolidation_arc_20260719')::uuid, 'private', 'private', 'architecture',
  'Arco de regime 2026-07-19: DXY 1D live + Layer1 1D = autoridade macro + E0/E2 vozes convergentes + consolidacao 1 daemon + entry-router dry',
  'Cinco passos executados 2026-07-19 (mercado fechado). (1) DXY 1D FEED: bar-store le a tab TVC:DXY pinada (tab_pin cache namespaced por (simbolo,res)) e estende o canonico raw_dxy_1d.jsonl (mesma proveniencia que validou o Layer1; 0 dup, monotonico). Leitor unico, sem contencao. (2) LAYER1 1D LIVE: macro_structural_v3.build_layer1() posto a correr live via Opcao A = matematica CONGELADA intocada, o service so injeta fonte fresca nos globais (XAU 1D = REV hist + store tail; DXY = store) + GATE DE PARIDADE (2981 barras historicas byte-identicas). Regime atual BEAR (bate o v5-4H). (3) E0/E2: dossie ganha axes.regime = 2 vozes convergentes (v5-4H + Layer1-1D), aditivo, NUNCA veto; E2 render_composite mostra ambas no # MACRO; regime() proxy e vetos intocados. (4) CONSOLIDACAO: o Layer1 foi FUNDIDO no regime-engine (daemon UNICO de regime corre v5-4H auxiliar + Layer1 1D autoridade no mesmo ciclo); daemon separado com.cristrein.layer1-service RETIRADO (criado e retirado no mesmo dia). (5) ENTRY-ROUTER 15M LIVE em DRY (com.cristrein.xau-entry-router): roteia camada de entry por regime (autoridade Layer1 1D) -- BEAR->Cp (dormante, sem duplicar) / RANGE->engine B v1.1 b_signal (dry-ledger) / BULL->A1/A2 pendente. Roteamento por contexto, NAO hard-gate. B le a autoridade fresca (Conexao 3, injeta antes de importar b_engine; probe off macro:BEAR). SEM Telegram (dry). Watchdog=19. CAVEAT: banda do B precisa 15M desde o onset do range (store=30d) -> flag band_truncated; go-live do B exige depois montagem 15M profundo + paridade + prereg. Commits c3f7c9b/15f4eaf/02d6bae/8378947/b1cd3e1.',
  array['seed:memory_delta_20260719_regime_consolidation_audit','regime','layer1','dxy','router','consolidacao','arquitetura'],
  'memory/reference_live_stack_20260718.md · commits c3f7c9b/15f4eaf/02d6bae/8378947/b1cd3e1', 'active'),
 (md5('v5_4h_consumer_audit_decision_A_20260719')::uuid, 'private', 'private', 'project',
  'Auditoria consumidores do v5-4H + decisao Cris = OPCAO A (manter como auxiliar)',
  'Auditoria read-only 2026-07-19. Achado: o OUTPUT do v5-4H (current_regime.json) tem UM so consumidor live = E0 context_engine.py (a voz adicionada 2026-07-19); antes disso NENHUM processo live lia o valor do v5. L1/L2/Cp NAO dependem dele: L2 tem regime_at() proprio interno em l2_engine.py; Cp auto-seleciona BEAR pela estrutura; L1 nao le current_regime.json. O detetor engine_4h_regime_gate_RAW so e importado por scripts de research/labs offline + o produtor. Funcao live real do v5 = alertas Telegram de transicao 4H (REGIME_TELEGRAM) + 2a voz convergente no E0. RETIRAR nao partiria nenhuma estrategia. DECISAO Cris = OPCAO A: MANTER o v5-4H como AUXILIAR (barato, corre no mesmo daemon, da aviso de transicao 4H mais rapido que o diario). Layer1 1D = autoridade macro; v5-4H = auxiliar. Auditoria e decisao gravadas p/ nao re-litigar.',
  array['seed:memory_delta_20260719_regime_consolidation_audit','v5-4h','auditoria','regime','decisao'],
  'memory/reference_live_stack_20260718.md (seccao REGIME CONSOLIDADO)', 'active'),
 (md5('feedback_consolidate_not_proliferate_20260719')::uuid, 'private', 'private', 'feedback',
  'Consolidar no APROVADO, nao proliferar processos/leituras novas em paralelo (Cris 2026-07-19)',
  'Feedback do Cris: tendencia recorrente a criar leituras/processos NOVOS paralelos em vez de consolidar na que ja estava aprovada. Caso: criei o Layer1 1D como daemon SEPARADO em vez de o consolidar no regime-engine; e historicamente o regime-engine live foi montado sobre v5-4H em vez do Layer1 1D "APROVADISSIMO" -> 4 leituras de regime a flutuar. Regra dura: antes de wire/daemon/leitura NOVA de algo que ja existe e foi aprovado, PARAR e perguntar se deve ADOTAR o aprovado como autoridade unica e estender o servico existente; default = consolidar; um servico por funcao, nao N. Mesmo espirito do RAW-first/proveniencia aplicado a PROCESSOS. Ficheiro-topico: feedback_consolidate_on_approved_not_new_process.',
  array['seed:memory_delta_20260719_regime_consolidation_audit','feedback','consolidar','processo','regime'],
  'memory/feedback_consolidate_on_approved_not_new_process.md', 'active')
on conflict (id) do nothing;
