-- ============================================================================
-- SUPABASE MEMORY — DELTA SEED · seed:memory_delta_20260730_xau_fomc_range_structure
-- ============================================================================
-- Conhecimento consolidado XAU pós-FOMC 29/07: chicote + veto-evento, range macro-estrutural, OB real vs pivo,
-- metodo ouro x DXY/EUR/petroleo. Aplicar via scripts/supabase/apply_memory_delta.py. Idempotente. 1 row.
-- ============================================================================
begin;
insert into memory_items (id, scope, visibility, category, title, body, tags, source_ref, status) values
(
  md5('seed:memory_delta_20260730_xau_fomc_range_structure:memory_items:knowledge')::uuid,
  'product', 'internal', 'reference',
  'XAU pos-FOMC 29/07 — RANGE macro-estrutural 3995-4116, OB real 3995-4010 (NAO 4042=pivo), CHoCH 4051, veto-de-evento, metodo ouro x DXY/EUR/petroleo (doc repo XAU_FOMC_RANGE_STRUCTURE_READ_20260730)',
  'Conhecimento consolidado (Cris pediu guardar 2026-07-30). Doc canonico versionado: docs/architecture/XAU_FOMC_RANGE_STRUCTURE_READ_20260730.md. (1) CHICOTE FOMC 29/07: HOLD 3.75%, baseline 4047 -> Powell dovish spike +59 ate 4116 em ~40min -> devolveu TUDO -> fechou 4045. Dovish moveu a FITA nao o PRECO (petroleo WTI +12.7 inflacao + real yield 2.41 seguraram o dolar). LICAO VETO-DE-EVENTO nos 2 sentidos: nao operar 3h antes de evento binario (E2 shortou @4001 pre-FOMC=timing hostil), nao narrar o pico como conclusao (Claude narrou +59 como reversao=ERRO, desfez-se). O que SALVA=processo: reader recusou 14 longs no dia, NENHUM na euforia do spike; regra so-long-com-reclaim-validado+nao-perseguir-esticado. Gestao de saida=trailing em momentum de evento (Cris fez +1600$ real FN->100350, podia ser ~3000$ com trailing no Powell; ver V_stair PDF). (2) RANGE MACRO-ESTRUTURAL 3995<->4116 (leitura RAW chart XAUUSD 60min via MCP OB Detector v11+SMC LuxAlgo+RSI+SVP): NAO e bear-a-continuar (erro corrigido) NEM acumulacao confirmada; preco no meio=pior sitio para entrar. (3) OB ESTRUTURAL REAL = 3995-4010 (order block). 4042 = PIVO SEM OB, nao estrutura. Long estrutural mora no OB nao no pivo. Regra: ler o OB que existe, nunca inventar nivel a mao. Supply acima: 4101-4116 (topo exato do spike FOMC=rejeicao), 4149-4166, 4183-4203+. Demand abaixo: 3995-4010, 3959-3976. (4) SMC=indecisao/range (BOS+CHoCH misturados); CHoCH em 4051=teto de momentum (reclaim >4051 tem significado, 2o gatilho). RSI 47.9<MA 54.7, volume vendedor domina mas enfraquece, NAS detector sem fundo. (5) METODO MACRO (contexto NAO validacao cross-asset; guard da falso-positivo): testar tese do ouro NO DOLAR. DXY 100.93 fraco (2024-25 andava 104-107), EURUSD 1.1453 euro forte. Ler via MCP trocando simbolo do chart (quote_get fica preso ao XAU pinado); bar-store=websocket Finnhub INDEPENDENTE (finnhub_gld_ws.py) nao o simbolo do chart, logo trocar NAO corrompe dados; restaurar PEPPERSTONE:XAUUSD 60min. Tickers TVC:DXY (o DXY simples resolve p/ XAUUSD), OANDA:EURUSD. 30/07: petroleo^->DXY recupera->EUR cai->dolar firma->sobe hipotese de testar OB 3995-4010 antes do repique. Arbitro=Core PCE 13:30. Vigia armado research/watch_demanda_reader_20260728.py em OB 3995-4010+CHoCH 4051 (toque=heads-up, reclaim=juizo do reader nunca mecanico). Boa chance de repique de alta no OB (tese Cris). Retoma dry 0/8 (mecanica compra repiques em bear/range=facas).',
  array['seed:memory_delta_20260730_xau_fomc_range_structure','xau-pos-fomc','chicote-spike-reverse','veto-de-evento','range-macro-estrutural-3995-4116','OB-real-3995-4010-nao-4042-pivo','choch-4051','metodo-ouro-x-dxy-eur-petroleo','trailing-gestao-saida','reader-recusou-14-longs'],
  'docs/architecture/XAU_FOMC_RANGE_STRUCTURE_READ_20260730.md · reference_xau_fomc_range_structure_read · project_fomc_29jul_win_and_trailing_lesson · research/watch_demanda_reader_20260728.py',
  'active'
)
on conflict (id) do nothing;
commit;
