#!/usr/bin/env python3
"""config/paths.py — central path/config resolver (Agentic OS Fase 2 portability layer).

ADDITIVE ONLY. This module changes nothing on its own: every root's DEFAULT equals the
current hardcoded absolute path, so importing/using it is byte-identical to today.
Every root is env-overridable (portability / commercialization). Never logs secret values.

Contract (env var -> safe default = current absolute path):
  TRADING_SYSTEM_ROOT   repo root                 default: <repo> (parent of config/)
  DATA_ROOT             data root                 default: = TRADING_SYSTEM_ROOT
  RAW_DATA_ROOT         RAW replay/source (HD)    default: /Volumes/GUTS_ LACIE/TradingData
  OUTPUT_ROOT           reports/outputs           default: <repo>/reports
  PRIVATE_ROOT          private research/strategy default: <repo>/my-strategy
  EXTERNAL_FACTOR_ROOT  EF v2 module              default: <repo>/external_factors_v2
  LOG_ROOT              logs                       default: <repo>/alert-bridge/logs
  TEMP_ROOT             scratch/bootstrap tmp     default: /tmp

Migration is opt-in per file (see docs/architecture/CONFIG_ENV_CONTRACT.md). Live scripts
are NOT changed here.
"""
from __future__ import annotations
import os
from pathlib import Path


def _repo_default() -> Path:
    # config/ lives directly under the repo root
    return Path(__file__).resolve().parents[1]


def _resolve(env_name: str, default) -> Path:
    v = os.environ.get(env_name)
    return Path(v) if v else Path(default)


def load_env() -> None:
    """Load .env (repo root + CWD) into os.environ via setdefault. Idempotent; never logs values."""
    root = _resolve("TRADING_SYSTEM_ROOT", _repo_default())
    seen = set()
    for envfile in (root / ".env", Path.cwd() / ".env"):
        try:
            key = envfile.resolve()
        except OSError:
            continue
        if key in seen or not envfile.is_file():
            continue
        seen.add(key)
        for line in envfile.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, val = line.partition("=")
            os.environ.setdefault(k.strip(), val.strip())


# Load .env before resolving roots so env overrides take effect. Safe on import.
load_env()

# --- 8 canonical roots (env override -> safe default = current absolute path) ---
TRADING_SYSTEM_ROOT: Path = _resolve("TRADING_SYSTEM_ROOT", _repo_default())
DATA_ROOT: Path = _resolve("DATA_ROOT", TRADING_SYSTEM_ROOT)
RAW_DATA_ROOT: Path = _resolve("RAW_DATA_ROOT", "/Volumes/GUTS_ LACIE/TradingData")
OUTPUT_ROOT: Path = _resolve("OUTPUT_ROOT", TRADING_SYSTEM_ROOT / "reports")
PRIVATE_ROOT: Path = _resolve("PRIVATE_ROOT", TRADING_SYSTEM_ROOT / "my-strategy")
EXTERNAL_FACTOR_ROOT: Path = _resolve("EXTERNAL_FACTOR_ROOT", TRADING_SYSTEM_ROOT / "external_factors_v2")
LOG_ROOT: Path = _resolve("LOG_ROOT", TRADING_SYSTEM_ROOT / "alert-bridge" / "logs")
TEMP_ROOT: Path = _resolve("TEMP_ROOT", "/tmp")


# --- helpers (return paths byte-identical to the current hardcoded literals) ---
def repo(*parts) -> Path:
    """Path under the repo root."""
    return TRADING_SYSTEM_ROOT.joinpath(*parts)


def tmp(name: str) -> Path:
    """Path under TEMP_ROOT (default /tmp). e.g. tmp('causal_segments_v10.json')."""
    return TEMP_ROOT / name


def raw(*parts) -> Path:
    """Path under RAW_DATA_ROOT (external HD RAW replay/source)."""
    return RAW_DATA_ROOT.joinpath(*parts)


def private(*parts) -> Path:
    """Path under PRIVATE_ROOT (my-strategy research/strategies)."""
    return PRIVATE_ROOT.joinpath(*parts)


def external_factor(*parts) -> Path:
    """Path under EXTERNAL_FACTOR_ROOT (external_factors_v2)."""
    return EXTERNAL_FACTOR_ROOT.joinpath(*parts)


def log(*parts) -> Path:
    """Path under LOG_ROOT."""
    return LOG_ROOT.joinpath(*parts)


def output(*parts) -> Path:
    """Path under OUTPUT_ROOT (reports)."""
    return OUTPUT_ROOT.joinpath(*parts)


def causal_segments() -> Path:
    """The reproducible RTSE bootstrap artifact (generated by phase10_hybrid_regime.py).
    Default byte-identical to '/tmp/causal_segments_v10.json'."""
    return TEMP_ROOT / "causal_segments_v10.json"


def ruler(*parts) -> Path:
    """Path under the L2/BPT revalidation results tree, e.g.
    ruler('XAU_4H_L2_BPT_BOS_CHOCH', 'v1', 'results', 'l2_bpt_regua_structural.csv')."""
    return PRIVATE_ROOT / "research" / "revalidation" / Path(*parts) if parts else PRIVATE_ROOT / "research" / "revalidation"


ALL_ROOTS = {
    "TRADING_SYSTEM_ROOT": TRADING_SYSTEM_ROOT,
    "DATA_ROOT": DATA_ROOT,
    "RAW_DATA_ROOT": RAW_DATA_ROOT,
    "OUTPUT_ROOT": OUTPUT_ROOT,
    "PRIVATE_ROOT": PRIVATE_ROOT,
    "EXTERNAL_FACTOR_ROOT": EXTERNAL_FACTOR_ROOT,
    "LOG_ROOT": LOG_ROOT,
    "TEMP_ROOT": TEMP_ROOT,
}


if __name__ == "__main__":
    # Print resolved roots (no secrets). Useful for `python config/paths.py`.
    for name, p in ALL_ROOTS.items():
        print(f"{name:22} = {p}")
    print(f"{'causal_segments()':22} = {causal_segments()}")
